   #include<iostream.h>
#include<conio.h>

void main()
{
		clrscr;
      cout<<"vv         vv     aaaaaaaaa      nnnn     nn"<<endl;
      cout<<" vv       vv      aaaaaaaaa      nn nn    nn"<<endl;
      cout<<"  vv     vv       aa     aa      nn  nn   nn"<<endl;
      cout<<"   vv   vv        aaaaaaaaa      nn   nn  nn"<<endl;
      cout<<"    vv vv         aa     aa      nn    nn nn"<<endl;
      cout<<"     vvv          aa     aa      nn     nnnn "<<endl;
getch();
}