#include<iostream.h>
#include<conio.h>

void main()
{
		clrscr;
      cout<<"aaaaaaaaa     ggggggggg      uu     uu"<<endl;
      cout<<"aaaaaaaaa     ggggggggg      uu     uu"<<endl;
      cout<<"aa     aa     gg             uu     uu"<<endl;
      cout<<"aa     aa     gg  ggggg      uu     uu"<<endl;
      cout<<"aaaaaaaaa     gg  ggggg      uu     uu"<<endl;
      cout<<"aa     aa     gg     gg      uu     uu"<<endl;
      cout<<"aa     aa     ggggggggg      uuuuuuuuu"<<endl;
      cout<<"aa     aa     ggggggggg      uuuuuuuuu"<<endl;
getch();
}